FROM node:18 AS react_build
WORKDIR /app
COPY client/my-app/package*.json ./
RUN npm install
COPY client/my-app/ .
RUN npm run build
RUN echo "==== Build contents ====" && ls -l build && echo "======================="

FROM nginx:alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=react_build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
