services:
  backend:
    build:
      context: ./server
    container_name: backend
    image: sportspro-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=sportprodb
      - PG_PORT=5432
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    container_name: nginx
    image: sportspro-nginx
    ports:
      - "8080:80" 
    depends_on:
      - backend

  postgres:
    image: postgres:14 
    container_name: sportspro_db 
    environment:
      POSTGRES_DB: sportprodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sportprodb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
